name: Analyze Issue
on: 
    issues:
        types: [opened]
jobs:
    output:
        runs-on: ubuntu-latest
        steps:
            - name: Outpout issue data
              run: echo "${{ toJSON(github.event) }}"

        