name: Deploy Project
on: push
jobs:
    analyze:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v3
            - name: Install node.js
              uses: actions/setup_node@v3
            - name: Install dependencies
              run: npm ci
            - name: Run lint check
              run: npm lint
